# Generated by Django 4.2.3 on 2024-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('work_style', models.CharField(max_length=200)),
                ('breakfast_time', models.DateField(verbose_name='Preferred breakfast time')),
                ('lunch_time', models.DateField(verbose_name='Preferred lunch time')),
                ('dinner_time', models.DateField(verbose_name='Preferred dinner time')),
            ],
        ),
    ]
